services:
  app_pg:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.pg
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_PG_HASURA_SERVICE_TOKEN_SECRET
      JDBC_SCHEMAS: $APP_PG_JDBC_SCHEMAS
      JDBC_URL: $APP_PG_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_PG_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_PG_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 6792:8080
